### ISSUE TITLE
Cursor places blow signature on reply

### ISSUE THREAD

**Issue by ttcc-gh** [Welpy-cw/Folder-Account#10]
Hi,

when I define a signature in my identity (in account settings directly or by using a file), folder-account places the cursor blow my email-signature when relying to message. This only happens if original recipient and identity mail address differs,

Example: Folder contains a message sent to "example@company". Folder account is set to use "other@company" in any cases for this folder. When replying to message, cursor gets placed below my signature.

It does not happen:

- when no signature is defined in identity
- when folder contans message to "other@example" and folder account is set to use "other@example" as reply identity.

Btw; by default, my messages alwas starts topmost, above any cites.

Br, Tom

**Comment by Welpy-cw** [comment]
Hi,

I already noticed this as well. Actually I think it's a bug in Thunderbird itself: If I disable Folder Account, start a reply, manually change the "From" identity to another one with a signature and press <TAB> twice to focus the editor, the cursor has moved to the bottom. Can you confirm this behavior?

Best, 
Welpy

**Comment by ttcc-gh** [comment]
Yes, you´re  right! I can confirm this annoying problem is a TB issue...

**Comment by Welpy-cw** [comment]
I just found the corresponding [Bugzilla entry](https://bugzilla.mozilla.org/show_bug.cgi?id=118050), the bug was first reported over 21 years ago ...

**Comment by Welpy-cw** [comment]
@ttcc-gh The [latest pre-release](https://github.com/Welpy-cw/Folder-Account/releases) version contains a workaround for this bug. Please test and report any issues!

**Comment by ttcc-gh** [comment]
It works great! Thx for your work!
