### ISSUE TITLE
Folder Account is flagged as not compatible with Thunderbird Beta 103.0

### ISSUE THREAD

**Issue by shardrunner** [Welpy-cw/Folder-Account#13]
Hi,
just wanted to report, that Thunderbird Beta 103.0 flags this addon as incompatible and disables it.
I have not tested, if it really does not work, if installed manually.

**Comment by Welpy-cw** [comment]
@DerFisc It's just an internal value which has been set to 103.0 in the next version. Would you care to install the latest [pre-release version](https://github.com/Welpy-cw/Folder-Account/releases) and give any feedback? I'd like to upload v11.3 to the store soon!

**Comment by shardrunner** [comment]
Without much testing, it seems to work fine, like before
My identities are placed properly and the settings page for folders works.
