### ISSUE TITLE
Excessive permissions

### ISSUE THREAD

**Issue by alexolog** [Welpy-cw/Folder-Account#16]
Why does this add-on require "full unrestricted access to Thunderbird and your computer"?
This seems excessive for the provided functionality.

**Comment by Welpy-cw** [comment]
Please see explanation [here](https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions#w_have-full-unrestricted-access-to-thunderbird-and-your-computer).

**Comment by siffegh** [comment]
@Welpy-cw - are the APIs you need still not there?

"Add-ons request this permission, as long as the new permission based API system does not yet offer the functionality they need."
