### ISSUE TITLE
Update needed for Thunderbird 125

### ISSUE THREAD

**Issue by moonlitbugs** [Welpy-cw/Folder-Account#18]
Folder Account (version 11.3.1) was working fine in Thunderbird 115.10, but is no longer being loaded by Thunderbird 125.

**Comment by Welpy-cw** [comment]
Please be advised version 125 isn't an official release, see this [announcement](https://thunderbird.topicbox.com/groups/planning/Tf458e19e4446e1c6/monthly-releases-update) in Topicbox.

Apart from that, you can use [version 11.3.2](https://github.com/Welpy-cw/Folder-Account/releases/tag/v11.3.2) from this website, which should work in 125 as well as in current Beta and Daily releases of Thunderbird.

**Comment by moonlitbugs** [comment]
Thanks for the quick update!  :smiley:
