### ISSUE TITLE
sort / search accounts

### ISSUE THREAD

**Issue by BK-20** [Welpy-cw/Folder-Account#4]
The feature I use very often is using a specific account per folder. Since I have several hundred accounts (aliases work fine to avoid SPAM), it is more and more painful to select the right one from the list of accounts. So it would be helpful to get the list sorted alphabetically or even searchable. Is it possible to implement this?

**Comment by Welpy-cw** [comment]
Thank you for your suggestion @BK-20, I was able to at least partially implement it. Please test the [latest pre-release](https://github.com/Welpy-cw/Folder-Account/releases) and report any issues.
