### ISSUE TITLE
Possible to use on Search Folders?

### ISSUE THREAD

**Issue by ailin-nemui** [Welpy-cw/Folder-Account#5]
Hi,

I am using saved searches to merge specific folders. Is it somehow possible to use assign a folder account to the saved search folder?

**Comment by Welpy-cw** [comment]
@ailin-nemui Sorry for the very late answer, but I came up with a workaround just recently: While you can't assign settings to a saved search directly, create a parent folder with the needed settings and move your saved search folder into it.

Another way would be to manually edit `prefs.js` and add the options for the search folders directly, but you really need to know what you are doing ...

**Comment by Welpy-cw** [comment]
This now works as expected with version 12.
