### ISSUE TITLE
Reply to all with multiple identities

### ISSUE THREAD

**Issue by gaubry** [Welpy-cw/Folder-Account#6]
I'd like to use always the same "From" mail address even when replying to a message that was sent to an alias. I created the appropriate identities, and in the Folder properties / Folder Account: I chose:
- From Account: my favorite identity
- I checked only "Use Reply-to address also on Reply and Forward"
The behavior is as expected when replying to a mail.
But, when doing "reply to all" to a message with multiple "To" received to an alternative identity:
- From is set to my default identity (as expected)
- my alternative identity is still in the "To" list (not expected: I send a message to me)

**Comment by Welpy-cw** [comment]
Thank you for your report @gaubry. After changing the way the add-on internally sets the fields in the message composition window, this issue should be resolved. Please test the [latest pre-release](https://github.com/Welpy-cw/Folder-Account/releases) and report any issues.

**Comment by Der-Achim** [comment]
@Welpy-cw Wow! It works great! And I see the name, email, idenity label and account name in the drop down box. That's really nice. Thank you for your great and fast help!
