### ISSUE TITLE
can't choose any identities

### ISSUE THREAD

**Issue by Der-Achim** [Welpy-cw/Folder-Account#7]
Since thunderbird-91.0.1 and Folder-Account 11.0 I can't choose any identities (only Accounts are visible in the drop down box).

**Comment by Welpy-cw** [comment]
Which operating system are you using, are there any other add-ons active? Does activating the new sort option change anything?

Using Thunderbird 91.0.1 (64-bit) for Windows (as well as different 91 betas under Xubuntu) I didn't encounter any problems yet ...

**Comment by Der-Achim** [comment]
Hi,

Operating System is Linux (Ubuntu 18.04), Activating the sort option did not help.

I configured 9 Accounts. In one of these accounts I configured 5 identities. One identity differs in the email address. This one is listed in Folder Account 11.0 as well.

But the other 4 only differ in Reply-To, CC, signature and identity label. In thunderbird 78 all 4 identities are visible, but they all looks the same, because only Account Name and [email address] is listed (idenity label would be helpful).

In thunderbird 91 only one of the 4 identities are listed.

**Comment by Welpy-cw** [comment]
Hi,

thank you for your detailed description. I just published a [new pre-release](https://github.com/Welpy-cw/Folder-Account/releases) version, could you please test it?

The ids in the drop-down menu are now shown as Thunderbird itself does it in the new-mail window. I hope that's ok.

**Comment by Welpy-cw** [comment]
> @Welpy-cw Wow! It works great! And I see the name, email, idenity label and account name in the drop down box. That's really nice. Thank you for your great and fast help!

@Der-Achim My pleasure! By the way, there is a new pre-release with small changes regarding the appearance of the drop-down menu, also changing the sorting behaviour. Maybe you'd like to try it out as well. If there are no regressions (I didn't notice any), I'll upload it to addons.thunderbird.net later.

**Comment by Der-Achim** [comment]
@Welpy-cw the seperation line betweem the accounts makes it clearer. I didn't encounter any problems with the 2nd pre-release. Thank you very much for your effort and for this very useful addon!
